### ISSUE TITLE
Chapter 9 - Adding the API - Page 193

### ISSUE THREAD

**Issue by pmarangoni** [PacktPublishing/Web-Development-with-Blazor#5]
In step #8, when I run the project I get an error. _**At the bottom of the browser it says**_ 
**An unhandled error has occurred. Reload**

Here are the errors displayed in the F12 devtools console:

>Refused to load the script 'https://localhost:44345/_framework/aspnetcore-browser-refresh.js' because it violates the following Content Security Policy directive: "script-src 'sha256-fa5rxHhZ799izGRP38+h4ud5QXNT0SFaFlh4eqDumBI='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

> blazor.webassembly.js:1 blazor Loaded 9.20 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.

> mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28

> dotnet-watch reload socket connected.

> Refused to load the script 'https://localhost:44345/_framework/aspnetcore-browser-refresh.js' because it violates the following Content Security Policy directive: "script-src 'sha256-fa5rxHhZ799izGRP38+h4ud5QXNT0SFaFlh4eqDumBI='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

> blazor.webassembly.js:1
>  TypeError: Failed to fetch
>     at Function.<anonymous> (blazor.webassembly.js:1)
>     at blazor.webassembly.js:1
>     at Object.next (blazor.webassembly.js:1)
>     at blazor.webassembly.js:1
>     at new Promise (<anonymous>)
>     at r (blazor.webassembly.js:1)
>     at Function.e.initAsync (blazor.webassembly.js:1)
>     at blazor.webassembly.js:1
>     at blazor.webassembly.js:1
>     at Object.next (blazor.webassembly.js:1)

> info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.

> info: System.Net.Http.HttpClient.Public.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:44345/MyBlogAPI/BlogPostCount

> info: System.Net.Http.HttpClient.Public.ClientHandler[100]
      Sending HTTP request GET https://localhost:44345/MyBlogAPI/BlogPostCount

> info: System.Net.Http.HttpClient.Public.ClientHandler[101]
      Received HTTP response headers after 26.5ms - 200

> info: System.Net.Http.HttpClient.Public.LogicalHandler[101]
      End processing HTTP request after 32.5ms - 200

> info: System.Net.Http.HttpClient.Public.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:44345/MyBlogAPI/BlogPosts?numberofposts=16&startindex=0

> info: System.Net.Http.HttpClient.Public.ClientHandler[100]
      Sending HTTP request GET https://localhost:44345/MyBlogAPI/BlogPosts?numberofposts=16&startindex=0

> info: System.Net.Http.HttpClient.Public.ClientHandler[101]
      Received HTTP response headers after 8.4ms - 200

> info: System.Net.Http.HttpClient.Public.LogicalHandler[101]
      End processing HTTP request after 9.4ms - 200

> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The JSON value could not be converted to System.Collections.Generic.List`1[MyBlog.Data.Models.BlogPost]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[MyBlog.Data.Models.BlogPost]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2[[System.Collections.Generic.List`1[[MyBlog.Data.Models.BlogPost, MyBlog.Data.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[MyBlog.Data.Models.BlogPost, MyBlog.Data.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[MyBlog.Data.Models.BlogPost, MyBlog.Data.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[MyBlog.Data.Models.BlogPost, MyBlog.Data.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[List`1](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[List`1](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.<ReadAsync>d__20`1[[System.Collections.Generic.List`1[[MyBlog.Data.Models.BlogPost, MyBlog.Data.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__3`1[[System.Collections.Generic.List`1[[MyBlog.Data.Models.BlogPost, MyBlog.Data.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__9`1[[System.Collections.Generic.List`1[[MyBlog.Data.Models.BlogPost, MyBlog.Data.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at MyBlog.Data.MyBlogApiClientSide.GetBlogPostsAsync(Int32 numberofposts, Int32 startindex) in D:\Repos\MyBlog\MyBlog.Data.Shared\MyBlogApiClientSide.cs:line 40
   at MyBlog.Shared.Pages.Index.LoadPosts(ItemsProviderRequest request) in D:\Repos\MyBlog\MyBlog.Shared\Pages\Index.razor:line 27
   at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1[[MyBlog.Data.Models.BlogPost, MyBlog.Data.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

>

**Comment by pmarangoni** [comment]
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The JSON value could not be converted to System.Collections.Generic.List`1[MyBlog.Data.Models.BlogPost]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[MyBlog.Data.Models.BlogPost]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)

**Comment by pmarangoni** [comment]
I see that in my MyBlogWebAssembly.Shared.csproj project I have this:
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
</Project>
`
But yours here in github is like this:
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

</Project>`

**Comment by pmarangoni** [comment]
I think I see what is wrong. MyBlogApiClientSide.cs is missing the following:
```
        System.Text.Json.JsonSerializerOptions jsonoptions = new System.Text.Json.JsonSerializerOptions
        {
            ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.Preserve,
            PropertyNamingPolicy = null
        };
```

**Comment by EngstromJimmy** [comment]
You are right!
Great find!
It is in the source on GitHub but it seems the code in the book is from an older iteration.
Thanks for letting me know!
